run:
  concurrency: 4
  timeout: 5m

linters-settings:
  gosec:
    excludes:
      - G104 # Handled by errcheck
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4
  cyclop:
    max-complexity: 15
  misspell:
    ignore-words:
      - ect
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - (or|er)$
      - tempFile

linters:
  enable-all: true
  disable:
    - staticcheck
    - varnamelen
    - gochecknoglobals
    - funlen
    - godox
    - wsl
    - nlreturn
    - gomnd
    - paralleltest
    - wrapcheck
    - testpackage
    - gofumpt
    - forbidigo
    - exhaustruct
    - nonamedreturns
    - tagliatelle
    - gomoddirectives
    - ireturn
    # Deprecated
    - exportloopref
    - execinquery
    - copyloopvar
    # Seems to be broken and just reports all the time.
    - depguard
    # Lots of noise
    - mnd
    - musttag
    # We're ok with dynamic errors
    - err113

issues:
  exclude:
    - .*Duplicate words \(.\.\) found.*
    - ^Error return value of `fmt\.\w+` is not checked.*
  exclude-use-default: false
  max-same-issues: 0
