version: "2"
run:
  concurrency: 4
linters:
  default: all
  disable:
    - copyloopvar
    # Seems to be broken and just reports all the time.
    - depguard
    # We're ok with dynamic errors
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - godox
    - gomoddirectives
    - ireturn
    - nlreturn
    - nonamedreturns
    - paralleltest
    - staticcheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    # Lots of noise
    - mnd
    - musttag
    # We prefer inline errors, and fix results in broken code.
    - noinlineerr
    # Noisy with types which extend time.Time
    - recvcheck
    # No real value for consumers as only exports methods are documented.
    - funcorder
    # Can result in increased struct size.
    - embeddedstructfieldcheck
    # Needs API changes.
    - noctx

  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 4
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G104
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
        - tempFile
    misspell:
      ignore-rules:
        - ect
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: .*Duplicate words \(.\.\) found.*
      - path: (.+)\.go$
        text: ^Error return value of `fmt\.\w+` is not checked.*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
