[root]
Verbose = 0

[gopro.convert]
Binary = "ffmpeg"
Args = [
	"-y",
	"-safe", "0",
	"-f", "concat",
	"-i", "",
	"-c:a", "copy",
	"-c:d", "copy",
	"-c:v", "libx264",
	"-vf", "scale=1920:1080",
	"-copy_unknown",
	"-map_metadata", "0",
	"-movflags", "use_metadata_tags",
	"-map", "0:v",
	"-map", "0:a",
	"-map", "0:m:handler_name:\tGoPro TCD",
	"-map", "0:m:handler_name:\tGoPro MET",
	"-map", "0:m:handler_name:\tGoPro SOS"
]
OutputDir = ""
SourceDir = "."
OutputTemplate = "{{.Name}}-JOINED{{.Ext}}"
LogLevel = "warn"
Overwrite = false # Overwrite existing files.
SkipNames = [] # Filenames to skip

[convert]
Decoder = "trackaddict"
Encoder = "laptimer"
Compress = false
Track = ""
Vehicle = ""
Tags = []
Note = ""
